### ISSUE TITLE
"Invalid cookie header" error on some soups

### ISSUE THREAD

**Issue by fadenb** [nathell/soupscraper#5]
Hey,

I wanted to give soupscraper a try on my soup `fadenb.soup.io`. Unfortunately it fails with only the error below in the log: 

`
[2020-07-21T16:30:28,474][WARN ][o.a.h.c.p.ResponseProcessCookies] Invalid cookie header: "set-cookie: soup_pool=B; domain=.soup.io; path=/; expires=Wed, 22 Jul 2020 16:30:15 -0000". Invalid 'expires' attribute: Wed, 22 Jul 2020 16:30:15 -0000
`

Other soups (e.g. `gaf.soup.io`) seem to work fine.

I am currently using `java -Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2 -jar soupscraper-0.1.0.jar fadenb` to start the application.

Full output:

```
[fadenb@miscos:~/soupscraper]$ java -Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2 -jar soupscraper-0.1.0.jar fadenb
This is Soupscraper v0.1.0
Downloading infiniscroll pages...
1 pages fetched, going back as far as null
Downloading assets...

Generating local copy...
Saving assets (this may take a while)...
Generating viewable soup...

[fadenb@miscos:~/soupscraper]$
[fadenb@miscos:~/soupscraper]$ ping fadenb.soup.io
PING fadenb.soup.io (45.153.143.247) 56(84) bytes of data.
64 bytes from soup.io (45.153.143.247): icmp_seq=1 ttl=56 time=9.25 ms
^C
--- fadenb.soup.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.254/9.254/9.254/0.000 ms

[fadenb@miscos:~/soupscraper]$
```

Anything I can do on my side to work around this issue?

Thanks!

**Comment by nathell** [comment]
Hey,

I am unable to reproduce this, but it seems to be an issue with Soupscraper having cached something it shouldn't have cached. Assuming you have set up `/etc/hosts` as recommended, can you do

```sh
rm ~/skyscraper-data/cache/html/soup/fadenb/list/latest
```

and retry?

Actually, before removing that file, please attach it to this issue – it will help figure out what's going on.

**Comment by fadenb** [comment]
Sorry, I was toying around and removed that file before I saw your comment.
Removing it seems to have helped the issue. I might have executed soupscraper before I modified the `/etc/hosts` causing it to break.

Working fine now (when soup does not throw a 503 ;) ).
Thanks!
